version: '3'
services:
  172.16.0.4:
    build: .
    networks:
      chord:
        ipv4_address: 172.16.0.4
  172.16.0.5:
    build: .
    networks:
      chord:
        ipv4_address: 172.16.0.5
  172.16.0.6:
    build: .
    networks:
      chord:
        ipv4_address: 172.16.0.6
  172.16.0.7:
    build: .
    networks:
      chord:
        ipv4_address: 172.16.0.7
  172.16.0.8:
    build: .
    networks:
      chord:
        ipv4_address: 172.16.0.8
  172.16.0.9:
    build: .
    networks:
      chord:
        ipv4_address: 172.16.0.9
  172.16.0.10:
    build: .
    networks:
      chord:
        ipv4_address: 172.16.0.10
  172.16.0.11:
    build: .
    networks:
      chord:
        ipv4_address: 172.16.0.11
  172.16.0.12:
    build: .
    networks:
      chord:
        ipv4_address: 172.16.0.12
  172.16.0.13:
    build: .
    networks:
      chord:
        ipv4_address: 172.16.0.13
  172.16.0.14:
    build: .
    networks:
      chord:
        ipv4_address: 172.16.0.14
  172.16.0.15:
    build: .
    networks:
      chord:
        ipv4_address: 172.16.0.15
  172.16.0.16:
    build: .
    networks:
      chord:
        ipv4_address: 172.16.0.16
  172.16.0.17:
    build: .
    networks:
      chord:
        ipv4_address: 172.16.0.17
  172.16.0.18:
    build: .
    networks:
      chord:
        ipv4_address: 172.16.0.18
  172.16.0.19:
    build: .
    networks:
      chord:
        ipv4_address: 172.16.0.19
  172.16.0.20:
    build: .
    networks:
      chord:
        ipv4_address: 172.16.0.20
  172.16.0.21:
    build: .
    networks:
      chord:
        ipv4_address: 172.16.0.21
  172.16.0.22:
    build: .
    networks:
      chord:
        ipv4_address: 172.16.0.22
networks:
  chord:
    ipam:
      config:
      -
        subnet: 172.16.0.0/24