p2p:
  dhash:
    resource-directory: out/dhash/
    replication-amount: 1
  chord:
    stable-ring-time: 2000
    stable-ring-thread-pool: 1
    key-length: 16
communication:
  socket:
    instances:
      dhash:
        RESPONSE_TIME: 2000
        BUFFER_SIZE_MULTICAST: 1024
        IP_MULTICAST: 224.0.0.1
        PORT_MULTICAST: 22011
        PORT_TCP_RESOURCE: 22012
        PORT_TCP: 22013
        PORT_UDP: 22014
        BUFFER_SIZE_UDP: 1024