version: '3'
services:
  172.16.0.43:
    build: .
    ports:
      - 23001:8080
    networks:
      chord:
        ipv4_address: 172.16.0.43
    volumes:
      - ./build/dhash:/build/dhash
  172.16.0.4:
    build: .
    ports:
      - 23002:8080
    networks:
      chord:
        ipv4_address: 172.16.0.4
    volumes:
      - ./build/dhash:/build/dhash
  172.16.0.5:
    build: .
    ports:
      - 23003:8080
    networks:
      chord:
        ipv4_address: 172.16.0.5
    volumes:
      - ./build/dhash:/build/dhash
  172.16.0.6:
    build: .
    ports:
      - 23004:8080
    networks:
      chord:
        ipv4_address: 172.16.0.6
    volumes:
      - ./build/dhash:/build/dhash
  172.16.0.7:
    build: .
    ports:
      - 23005:8080
    networks:
      chord:
        ipv4_address: 172.16.0.7
    volumes:
      - ./build/dhash:/build/dhash
  172.16.0.8:
    build: .
    ports:
      - 23006:8080
    networks:
      chord:
        ipv4_address: 172.16.0.8
    volumes:
      - ./build/dhash:/build/dhash
  172.16.0.9:
    build: .
    ports:
      - 23007:8080
    networks:
      chord:
        ipv4_address: 172.16.0.9
    volumes:
      - ./build/dhash:/build/dhash
  172.16.0.10:
    build: .
    ports:
      - 23008:8080
    networks:
      chord:
        ipv4_address: 172.16.0.10
    volumes:
      - ./build/dhash:/build/dhash
  172.16.0.11:
    build: .
    ports:
      - 23009:8080
    networks:
      chord:
        ipv4_address: 172.16.0.11
    volumes:
      - ./build/dhash:/build/dhash
  172.16.0.12:
    build: .
    ports:
      - 23010:8080
    networks:
      chord:
        ipv4_address: 172.16.0.12
    volumes:
      - ./build/dhash:/build/dhash
  172.16.0.13:
    build: .
    ports:
      - 23011:8080
    networks:
      chord:
        ipv4_address: 172.16.0.13
    volumes:
      - ./build/dhash:/build/dhash
  172.16.0.14:
    build: .
    ports:
      - 23012:8080
    networks:
      chord:
        ipv4_address: 172.16.0.14
    volumes:
      - ./build/dhash:/build/dhash
  172.16.0.15:
    build: .
    ports:
      - 23013:8080
    networks:
      chord:
        ipv4_address: 172.16.0.15
    volumes:
      - ./build/dhash:/build/dhash
  172.16.0.16:
    build: .
    ports:
      - 23014:8080
    networks:
      chord:
        ipv4_address: 172.16.0.16
    volumes:
      - ./build/dhash:/build/dhash
  172.16.0.17:
    build: .
    ports:
      - 23015:8080
    networks:
      chord:
        ipv4_address: 172.16.0.17
    volumes:
      - ./build/dhash:/build/dhash
  172.16.0.18:
    build: .
    ports:
      - 23016:8080
    networks:
      chord:
        ipv4_address: 172.16.0.18
    volumes:
      - ./build/dhash:/build/dhash
  172.16.0.19:
    build: .
    ports:
      - 23017:8080
    networks:
      chord:
        ipv4_address: 172.16.0.19
    volumes:
      - ./build/dhash:/build/dhash
  172.16.0.20:
    build: .
    ports:
      - 23018:8080
    networks:
      chord:
        ipv4_address: 172.16.0.20
    volumes:
      - ./build/dhash:/build/dhash
  172.16.0.21:
    build: .
    ports:
      - 23019:8080
    networks:
      chord:
        ipv4_address: 172.16.0.21
    volumes:
      - ./build/dhash:/build/dhash
  172.16.0.22:
    build: .
    ports:
      - 23020:8080
    networks:
      chord:
        ipv4_address: 172.16.0.22
    volumes:
      - ./build/dhash:/build/dhash
networks:
  chord:
    ipam:
      config:
      -
        subnet: 172.16.0.0/24